#!/bin/bash
PREFIX=${CHAT_NODE_PREFIX}
NUMNODES=${CHAT_NODES}
PORT=1
DELAY=0
SUFFIX=${CHAT_NO}
echo "checking memory on nodes..."

until [ $PORT -gt "$NUMNODES" ]
do
    HOST=${PREFIX}${PORT}
    echo "${HOST}"
    ssh pi@${HOST} free -h
    sleep ${DELAY}
    ((PORT++))
done
echo "node check complete"
