#!/bin/bash
# start_nfs - make sure NFS services are started
echo "starting NFS services..."
echo -n "rpcbind..."
sudo service rpcbind start
echo "$?"
echo "==> sleep for 5 seconds..."
sleep 5
echo -n "nfs server..."
sudo service nfs-kernel-server restart
echo "$?"
